services:
    chat-server:
        image: chat-server:latest
        build: ./chat-server/
        networks:
          - main-network
        ports:
          - target: 80
            published: 80
            protocol: tcp
        env_file:
          - ./chat-server/.env.docker
    db:
        image: redis:7.0.5-bullseye
        networks:
          - main-network
        ports:
          - target: 6379
            published: 6379
            protocol: tcp
    mq:
        image: rabbitmq:3.11.5
        networks:
          - main-network
        ports:
          # amqp
          - target: 5672
            published: 5672
            protocol: tcp
          # management console
          - target: 15672
            published: 15672
            protocol: tcp
        env_file:
          - .env.rabbitmq
            
networks:
    main-network:
