# Use this compose to locally test the system

services:
    chat-server:
        image: meepo-chat-server:latest
        build: ./chat-server/
        restart: unless-stopped
        networks:
          - main-network
        ports:
          - target: 80
            published: ${ADVERTISED_PORT}
            protocol: tcp
        env_file:
          - .env
        depends_on:
            mq:
                condition: service_healthy
            db:
                condition: service_started
    db:
        image: redis:7.0.5-bullseye
        restart: unless-stopped
        networks:
          - main-network
        ports:
          - target: 6379
            published: 6379
            protocol: tcp
    mq:
        image: rabbitmq:3.11.5
        restart: unless-stopped
        networks:
          - main-network
        ports:
          # amqp
          - target: 5672
            published: 5672
            protocol: tcp
          # management console
          - target: 15672
            published: 15672
            protocol: tcp
        env_file:
          - .env
        healthcheck:
            test: ["CMD", "rabbitmqctl", "list_queues"]
            interval: 10s
            timeout: 8s
            retries: 5
    logger:
        image: meepo-logger:latest
        build: ./logger/
        restart: unless-stopped
        networks:
          - main-network
        env_file:
          - .env
        depends_on:
            mq:
                condition: service_healthy
    # master-server:
    # front-end:
            
networks:
    main-network:
