version: "3.8"
services:
  front-end:
    image: pikrog/meepo-front-end:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
  logger:
    environment:
      BROKER_URL: amqp://user:password@mq
      DATABASE_URL: postgresql://user:password@main-db/meepo
    image: meepo-logger:latest
    networks:
      meepo-chat-network: null
  main-db:
    deploy:
      placement:
        constraints:
        - node.labels.maindb == true
    environment:
      POSTGRES_DB: meepo
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    image: postgres:15.0
    networks:
      meepo-chat-network: null
    volumes:
    - type: volume
      source: postgres-data
      target: /var/lib/postgresql/data
  master-server:
    environment:
      BACKEND_CORS_ORIGINS: '["http://localhost:8000", "https://localhost:8000", "http://localhost",
        "https://localhost", "http://localhost:9999"]'
      BROKER_URL: amqp://user:password@mq
      DATABASE_URL: postgresql://user:password@main-db/meepo
      JWT_SECRET: super_secret
    image: pikrog/meepo-master-server:latest
    networks:
      meepo-chat-network: null
    ports:
    - target: 80
      published: 8080
      protocol: tcp
  mq:
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: user
    image: rabbitmq:3.11.5
    networks:
      meepo-chat-network: null
networks:
  meepo-chat-network:
    name: meepo-chat-network
    driver: overlay
    external: true
    attachable: true
volumes:
  postgres-data:
    name: pr_postgres-data
